Update FAQ
Grace-Hacks/grace-hacks.github.io pull request #32
Opened 2020-10-08 01:57 UTC by mpadil18

Updated the .css and .js files.
Added vector images per the figma file.

2020-10-08 04:43 UTC, tim-nguyen-cs requested changes
@mpadil18 I really like how this looks! I can see how you paid attentioned to responsiveness and implemented it very much like the Figma design, so great job!

I made a comment on some of the things that I noticed, but the design team recently approved our use of Material UI's "Accordion" component, so see if you can take a look at some other sections to see if you can implement that instead.

2020-10-08 04:43 UTC, tim-nguyen-cs commented on src/components/FAQ/FAQ.js
> +import './FAQ.css';
The styling isn't working correctly because this file name is incorrect. Change it back to `*.scss` and it should work better.

2020-10-08 04:43 UTC, tim-nguyen-cs commented on src/components/FAQ/FAQ.scss
> +}
What's great about SCSS is that we can nest these styles now. Take a look at how they were implemented before and see if you can nest them now.

2020-10-08 04:43 UTC, tim-nguyen-cs commented on src/components/FAQ/FAQ.js
> +import './FAQ.css';
Make sure to compile your code too, because that's where the error's caught again.

2020-10-08 04:43 UTC, tim-nguyen-cs commented on src/components/FAQ/FAQ.js
> +          <div class="faq-title" onClick={() => {toggleState("one")}}><div class= 'ques'>What is a hackathon?</div> <img src={require("./vector.png")} class="arrow"/></div>
Make sure to keep class styling consistent and remove the space in `class= 'ques'`.

2020-10-17 04:06 UTC, sarah-avila commented
@tim-nguyen-cs This looks really good! I quickly imported the Nunito font and adjusted the spacing a bit, but this looks ready to merge!

2020-10-17 04:07 UTC, merged